### ISSUE TITLE
Sample rate 

### ISSUE THREAD

**Issue by SherlockShemol** [vocaliodmiku/wav2vec2mdd-Text#4]
您好，我尝试跑通您的代码。环境都已经安装完成，路径也已修改好，但是仍然出现报错。
![image](https://user-images.githubusercontent.com/87739402/186583558-1d104da6-0faf-4097-a47e-18f18a3edffe.png)
显示需要16000采样率而目前是44100，如果把代码中采样率改为44100的话，则报错又显示为：需要44100，目前是16000.请问您遇到过这样的问题吗？是数据集的问题吗，还是其他问题呢？

**Comment by SherlockShemol** [comment]
身边一位同学也遇到了同样的问题，恳请您不吝赐教

**Comment by vocaliodmiku** [comment]
是的，这个代码中的采样率是指输入的采样率，这里只能是16000. 按理来说改成44100的话，我们预期的情况是他可以自动适应44100，但是实际情况是我们要自己将44100的语音重采样到16000才行。使用sox 之类的工具。

**Comment by SherlockShemol** [comment]
感谢，我们已经使用sox解决此问题。
