### ISSUE TITLE
How do I modify code for data augmentation?

### ISSUE THREAD

**Issue by teinhonglo** [vocaliodmiku/wav2vec2mdd-Text#5]
Thanks for the work you do. I am getting very nice performance on the L2-ARCTIC.
Due to I'm a rookie of the fairseq, so I have a little bit of questions for experiment.

How do I modify the code for SpecAugmet and mask for the input of wav2vec2 and prompt, respectively?

I noticed that dataloader is here.
[https://github.com/vocaliodmiku/wav2vec2mdd-Text/blob/9063aafee731421bcae59f7e71ed9accfbb9a87c/fairseq/fairseq/tasks/text_condition.py#L314](https://github.com/vocaliodmiku/wav2vec2mdd-Text/blob/9063aafee731421bcae59f7e71ed9accfbb9a87c/fairseq/fairseq/tasks/text_condition.py#L314)

and the definition of the model structure is here.
[https://github.com/vocaliodmiku/wav2vec2mdd-Text/blob/9063aafee731421bcae59f7e71ed9accfbb9a87c/fairseq/fairseq/models/wav2vec/wav2vec2_sigmoid.py#L352](https://github.com/vocaliodmiku/wav2vec2mdd-Text/blob/9063aafee731421bcae59f7e71ed9accfbb9a87c/fairseq/fairseq/models/wav2vec/wav2vec2_sigmoid.py#L352)

But I still don't figure out how do I achieve a goal that I mentioned above (training: augment, inference: nothing).
Any suggestions are very appreciated.

Many thanks.

**Comment by vocaliodmiku** [comment]
fairseq is kind of liitle bit complex i think too. The CNN module receives sample point and output featrue map, and corresponding forward is follow:
https://github.com/vocaliodmiku/wav2vec2mdd-Text/blob/9063aafee731421bcae59f7e71ed9accfbb9a87c/fairseq/fairseq/models/wav2vec/wav2vec2.py#L473
and you can add SpecAugment Anywhere you want.
For the inference, the script will use the same code. So if you don't want to make thing complex, i recommend to train with modified code (i.e. add SpecAugment), and comment modified part when doging inference even it sounds weird. 
Let me know if you have any touble.

**Comment by teinhonglo** [comment]
Thanks for your quickly reply.
I implement SpecAugment based on your suggestion above in this week.

In addition, I have one question.
1. How about implement text mask (such as masked LM) for reference text (or called prompt)?

Many thanks.

**Comment by vocaliodmiku** [comment]
I think text mask applied in masked LM aims to build the context information while CAPT pays more attention to acoustic cues. But there is no any result i can provide for above statement, you can have a try on it.
What's more, one of the key problems of CAPT is the low availability of mispronouced speech data. maybe you can design different text masks (e.g. generate persudo text  sequence to simulate mispronunciations) to alleviate it.

**Comment by teinhonglo** [comment]
Thanks for your suggestion.
I will try it in two weeks.
